insert into config_province (province_code, province_name) VALUES (110, '北京');
insert into config_province (province_code, province_name) VALUES (120, '天津');
insert into config_province (province_code, province_name) VALUES (130, '河北');
insert into config_province (province_code, province_name) VALUES (140, '山西');
insert into config_province (province_code, province_name) VALUES (150, '内蒙古');
insert into config_province (province_code, province_name) VALUES (210, '辽宁');
insert into config_province (province_code, province_name) VALUES (220, '吉林');
insert into config_province (province_code, province_name) VALUES (230, '黑龙江');
insert into config_province (province_code, province_name) VALUES (310, '上海');
insert into config_province (province_code, province_name) VALUES (320, '江苏');
insert into config_province (province_code, province_name) VALUES (330, '浙江');
insert into config_province (province_code, province_name) VALUES (340, '安徽');
insert into config_province (province_code, province_name) VALUES (350, '福建');
insert into config_province (province_code, province_name) VALUES (360, '江西');
insert into config_province (province_code, province_name) VALUES (370, '山东');
insert into config_province (province_code, province_name) VALUES (410, '河南');
insert into config_province (province_code, province_name) VALUES (420, '湖北');
insert into config_province (province_code, province_name) VALUES (430, '湖南');
insert into config_province (province_code, province_name) VALUES (440, '广东');
insert into config_province (province_code, province_name) VALUES (450, '广西');
insert into config_province (province_code, province_name) VALUES (460, '海南');
insert into config_province (province_code, province_name) VALUES (500, '重庆');
insert into config_province (province_code, province_name) VALUES (510, '四川');
insert into config_province (province_code, province_name) VALUES (520, '贵州');
insert into config_province (province_code, province_name) VALUES (530, '云南');
insert into config_province (province_code, province_name) VALUES (540, '西藏');
insert into config_province (province_code, province_name) VALUES (610, '陕西');
insert into config_province (province_code, province_name) VALUES (620, '甘肃');
insert into config_province (province_code, province_name) VALUES (630, '青海');
insert into config_province (province_code, province_name) VALUES (640, '宁夏');
insert into config_province (province_code, province_name) VALUES (650, '新疆');

INSERT into config_candidate_info (province_code, candidate_name, candidate_type) VALUES (120, '白学军', 0);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type) VALUES (110, '蔡华俭', 0);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type) VALUES (330, '曹立人', 0);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type) VALUES (210, '常若松', 0);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type) VALUES (110, '车宏生', 0);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type) VALUES (500, '陈安涛', 0);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type) VALUES (110, '陈楚侨', 0);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type) VALUES (500, '陈红', 0);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type) VALUES (230, '陈健芷', 0);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type) VALUES (500, '陈旭', 0);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type) VALUES (110, '陈英和', 0);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type) VALUES (150, '陈中永', 0);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type) VALUES (110, '迟立忠', 0);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type) VALUES (360, '戴海琦', 0);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type) VALUES (320, '邓铸', 0);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type) VALUES (110, '董奇', 0);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type) VALUES (110, '樊富珉', 0);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type) VALUES (140, '范红霞', 0);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type) VALUES (110, '方方', 0);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type) VALUES (110, '方富熹', 0);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type) VALUES (110, '方平', 0);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type) VALUES (110, '方晓义', 0);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type) VALUES (500, '冯正直', 0);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type) VALUES (320, '傅宏', 0);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type) VALUES (110, '傅小兰', 0);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type) VALUES (220, '盖笑松', 0);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type) VALUES (110, '甘怡群', 0);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type) VALUES (440, '高定国', 0);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type) VALUES (370, '高峰强', 0);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type) VALUES (110, '高文斌', 0);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type) VALUES (310, '高湘萍', 0);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type) VALUES (330, '葛列众', 0);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type) VALUES (340, '葛明贵', 0);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type) VALUES (320, '郭本禹', 0);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type) VALUES (110, '郭春彦', 0);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type) VALUES (230, '郭德凤', 0);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type) VALUES (310, '郭秀艳', 0);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type) VALUES (420, '郭永玉', 0);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type) VALUES (110, '韩布新', 0);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type) VALUES (440, '何先友', 0);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type) VALUES (110, '洪炜', 0);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type) VALUES (110, '侯玉波', 0);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type) VALUES (110, '侯志瑾', 0);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type) VALUES (610, '胡卫平', 0);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type) VALUES (360, '胡竹菁', 0);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type) VALUES (440, '黄敏儿', 0);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type) VALUES (500, '黄希庭', 0);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type) VALUES (110, '贾晓明', 0);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type) VALUES (420, '江光荣', 0);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type) VALUES (110, '蒋毅', 0);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type) VALUES (110, '金盛华', 0);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type) VALUES (110, '寇彧', 0);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type) VALUES (110, '雷雳', 0);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type) VALUES (310, '李丹', 0);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type) VALUES (210, '李红', 0);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type) VALUES (150, '李慧', 0);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type) VALUES (110, '李玫瑾', 0);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type) VALUES (630, '李美华', 0);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type) VALUES (310, '李其维', 0);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type) VALUES (120, '李强', 0);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type) VALUES (370, '李寿欣', 0);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type) VALUES (110, '李纾', 0);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type) VALUES (330, '李伟健', 0);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type) VALUES (310, '李先春', 0);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type) VALUES (510, '李小融', 0);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type) VALUES (440, '李晓东', 0);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type) VALUES (110, '李新旺', 0);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type) VALUES (410, '李永鑫', 0);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type) VALUES (350, '连榕', 0);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type) VALUES (120, '梁福成', 0);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type) VALUES (310, '梁宁建', 0);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type) VALUES (110, '林崇德', 0);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type) VALUES (320, '刘昌', 0);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type) VALUES (320, '刘电芝', 0);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type) VALUES (420, '刘华山', 0);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type) VALUES (110, '刘力', 0);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type) VALUES (440, '刘鸣', 0);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type) VALUES (210, '刘文', 0);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type) VALUES (310, '刘晓虹', 0);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type) VALUES (220, '刘晓明', 0);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type) VALUES (610, '刘旭峰', 0);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type) VALUES (110, '刘勋', 0);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type) VALUES (310, '刘永芳', 0);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type) VALUES (110, '刘正奎', 0);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type) VALUES (110, '刘志宏', 0);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type) VALUES (420, '龙立荣', 0);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type) VALUES (310, '卢家楣', 0);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type) VALUES (130, '鲁忠义', 0);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type) VALUES (540, '罗桑平措', 0);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type) VALUES (110, '罗跃嘉', 0);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type) VALUES (120, '吕勇', 0);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type) VALUES (110, '马皑', 0);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type) VALUES (330, '马剑虹', 0);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type) VALUES (110, '毛志雄', 0);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type) VALUES (110, '梅建', 0);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type) VALUES (610, '苗丹民', 0);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type) VALUES (440, '聂衍刚', 0);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type) VALUES (310, '庞维国', 0);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type) VALUES (430, '彭运石', 0);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type) VALUES (110, '钱铭怡', 0);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type) VALUES (500, '秦启文', 0);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type) VALUES (110, '邱炳武', 0);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type) VALUES (500, '邱江', 0);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type) VALUES (310, '桑标', 0);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type) VALUES (110, '申继亮', 0);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type) VALUES (330, '沈模卫', 0);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type) VALUES (110, '施建农', 0);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type) VALUES (110, '时勘', 0);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type) VALUES (110, '舒华', 0);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type) VALUES (370, '宋广文', 0);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type) VALUES (110, '苏彦捷', 0);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type) VALUES (110, '隋南', 0);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type) VALUES (110, '孙健敏', 0);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type) VALUES (310, '孙时进', 0);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type) VALUES (110, '孙向红', 0);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type) VALUES (320, '谭顶良', 0);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type) VALUES (310, '唐宁玉', 0);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type) VALUES (110, '陶沙', 0);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type) VALUES (530, '陶云', 0);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type) VALUES (320, '田晓明', 0);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type) VALUES (120, '汪新建', 0);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type) VALUES (110, '王登峰', 0);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type) VALUES (130, '王京生', 0);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type) VALUES (110, '王垒', 0);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type) VALUES (370, '王美芳', 0);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type) VALUES (310, '王沛', 0);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type) VALUES (610, '王勇慧', 0);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type) VALUES (110, '王耘', 0);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type) VALUES (610, '王振宏', 0);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type) VALUES (330, '王重鸣', 0);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type) VALUES (450, '韦义平', 0);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type) VALUES (650, '闻素霞', 0);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type) VALUES (310, '吴庆麟', 0);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type) VALUES (110, '吴艳红', 0);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type) VALUES (110, '伍新春', 0);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type) VALUES (460, '肖少北', 0);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type) VALUES (510, '徐鸿', 0);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type) VALUES (110, '许燕', 0);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type) VALUES (120, '闫国利', 0);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type) VALUES (110, '杨波', 0);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type) VALUES (140, '杨继平', 0);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type) VALUES (210, '杨丽珠', 0);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type) VALUES (510, '杨彦春', 0);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type) VALUES (110, '杨玉芳', 0);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type) VALUES (340, '姚本先', 0);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type) VALUES (120, '姚家新', 0);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type) VALUES (430, '姚树桥', 0);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type) VALUES (440, '叶浩生', 0);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type) VALUES (610, '游旭群', 0);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type) VALUES (320, '余嘉元', 0);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type) VALUES (110, '俞国良', 0);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type) VALUES (500, '张大均', 0);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type) VALUES (330, '张锋', 0);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type) VALUES (110, '张厚粲', 0);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type) VALUES (110, '张建新', 0);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type) VALUES (110, '张侃', 0);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type) VALUES (110, '张力为', 0);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type) VALUES (640, '张丽锦', 0);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type) VALUES (350, '张灵聪', 0);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type) VALUES (440, '张敏强', 0);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type) VALUES (220, '张明', 0);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type) VALUES (210, '张奇', 0);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type) VALUES (500, '张庆林', 0);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type) VALUES (230, '张守臣', 0);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type) VALUES (440, '张卫', 0);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type) VALUES (370, '张文新', 0);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type) VALUES (220, '张向葵', 0);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type) VALUES (410, '赵国祥', 0);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type) VALUES (410, '赵俊峰', 0);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type) VALUES (520, '赵守盈', 0);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type) VALUES (310, '赵旭东', 0);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type) VALUES (330, '郑全全', 0);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type) VALUES (440, '郑希付', 0);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type) VALUES (440, '郑雪', 0);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type) VALUES (420, '钟年', 0);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type) VALUES (620, '周爱保', 0);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type) VALUES (110, '周晓林', 0);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type) VALUES (440, '周欣悦', 0);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type) VALUES (420, '周宗奎', 0);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type) VALUES (110, '朱莉琪', 0);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type) VALUES (110, '邹泓', 0);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type) VALUES (420, '佐斌', 0);
