insert into config_province (province_code, province_name) VALUES (110, '北京');
insert into config_province (province_code, province_name) VALUES (120, '天津');
insert into config_province (province_code, province_name) VALUES (130, '河北');
insert into config_province (province_code, province_name) VALUES (140, '山西');
insert into config_province (province_code, province_name) VALUES (150, '内蒙古');
insert into config_province (province_code, province_name) VALUES (210, '辽宁');
insert into config_province (province_code, province_name) VALUES (220, '吉林');
insert into config_province (province_code, province_name) VALUES (230, '黑龙江');
insert into config_province (province_code, province_name) VALUES (310, '上海');
insert into config_province (province_code, province_name) VALUES (320, '江苏');
insert into config_province (province_code, province_name) VALUES (330, '浙江');
insert into config_province (province_code, province_name) VALUES (340, '安徽');
insert into config_province (province_code, province_name) VALUES (350, '福建');
insert into config_province (province_code, province_name) VALUES (360, '江西');
insert into config_province (province_code, province_name) VALUES (370, '山东');
insert into config_province (province_code, province_name) VALUES (410, '河南');
insert into config_province (province_code, province_name) VALUES (420, '湖北');
insert into config_province (province_code, province_name) VALUES (430, '湖南');
insert into config_province (province_code, province_name) VALUES (440, '广东');
insert into config_province (province_code, province_name) VALUES (450, '广西');
insert into config_province (province_code, province_name) VALUES (460, '海南');
insert into config_province (province_code, province_name) VALUES (500, '重庆');
insert into config_province (province_code, province_name) VALUES (510, '四川');
insert into config_province (province_code, province_name) VALUES (520, '贵州');
insert into config_province (province_code, province_name) VALUES (530, '云南');
insert into config_province (province_code, province_name) VALUES (540, '西藏');
insert into config_province (province_code, province_name) VALUES (610, '陕西');
insert into config_province (province_code, province_name) VALUES (620, '甘肃');
insert into config_province (province_code, province_name) VALUES (630, '青海');
insert into config_province (province_code, province_name) VALUES (640, '宁夏');
insert into config_province (province_code, province_name) VALUES (650, '新疆');

INSERT into config_candidate_info (province_code, candidate_name, candidate_type, is_previous_staff) VALUES (220, '刘晓明', 0, 1);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type, is_previous_staff) VALUES (610, '苗丹民', 0, 1);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type, is_previous_staff) VALUES (310, '石文典', 0, 1);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type, is_previous_staff) VALUES (130, '宋耀武', 0, 1);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type, is_previous_staff) VALUES (530, '陶云', 0, 1);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type, is_previous_staff) VALUES (110, '许燕', 0, 0);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type, is_previous_staff) VALUES (410, '赵俊峰', 0, 1);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type, is_previous_staff) VALUES (370, '朱莉琪', 0, 1);

INSERT into config_candidate_info (province_code, candidate_name, candidate_type, is_previous_staff) VALUES (120, '白学军', 1, 1);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type, is_previous_staff) VALUES (310, '蔡丹', 1, 0);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type, is_previous_staff) VALUES (310, '陈安涛', 1, 1);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type, is_previous_staff) VALUES (110, '陈楚侨', 1, 1);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type, is_previous_staff) VALUES (500, '陈红', 1, 1);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type, is_previous_staff) VALUES (510, '陈华', 1, 0);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type, is_previous_staff) VALUES (330, '陈辉', 1, 0);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type, is_previous_staff) VALUES (440, '陈骐', 1, 0);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type, is_previous_staff) VALUES (440, '陈琦', 1, 0);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type, is_previous_staff) VALUES (320, '陈庆荣', 1, 0);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type, is_previous_staff) VALUES (110, '陈雪峰', 1, 1);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type, is_previous_staff) VALUES (110, '陈英和', 1, 1);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type, is_previous_staff) VALUES (520, '程刚', 1, 0);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type, is_previous_staff) VALUES (320, '邓铸', 1, 1);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type, is_previous_staff) VALUES (430, '丁道群', 1, 0);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type, is_previous_staff) VALUES (620, '丁小斌', 1, 0);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type, is_previous_staff) VALUES (440, '丁晓伟', 1, 0);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type, is_previous_staff) VALUES (360, '董圣鸿', 1, 1);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type, is_previous_staff) VALUES (210, '窦广波', 1, 0);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type, is_previous_staff) VALUES (440, '窦凯', 1, 0);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type, is_previous_staff) VALUES (110, '杜峰', 1, 0);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type, is_previous_staff) VALUES (110, '杜忆', 1, 0);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type, is_previous_staff) VALUES (210, '范会勇', 1, 0);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type, is_previous_staff) VALUES (110, '方方', 1, 1);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type, is_previous_staff) VALUES (110, '方平', 1, 1);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type, is_previous_staff) VALUES (110, '方晓义', 1, 1);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type, is_previous_staff) VALUES (500, '冯廷勇', 1, 1);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type, is_previous_staff) VALUES (320, '冯文锋', 1, 0);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type, is_previous_staff) VALUES (500, '冯正直', 1, 1);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type, is_previous_staff) VALUES (320, '伏干', 1, 0);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type, is_previous_staff) VALUES (310, '傅小兰', 1, 1);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type, is_previous_staff) VALUES (220, '盖笑松', 1, 1);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type, is_previous_staff) VALUES (110, '甘怡群', 1, 0);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type, is_previous_staff) VALUES (440, '高定国', 1, 1);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type, is_previous_staff) VALUES (370, '高峰强', 1, 1);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type, is_previous_staff) VALUES (220, '高申春', 1, 1);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type, is_previous_staff) VALUES (320, '郭本禹', 1, 1);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type, is_previous_staff) VALUES (110, '郭春彦', 1, 1);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type, is_previous_staff) VALUES (310, '郭秀艳', 1, 1);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type, is_previous_staff) VALUES (320, '郭永玉', 1, 1);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type, is_previous_staff) VALUES (110, '韩布新', 1, 1);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type, is_previous_staff) VALUES (310, '郝宁', 1, 0);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type, is_previous_staff) VALUES (410, '何安明', 1, 0);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type, is_previous_staff) VALUES (330, '何贵兵', 1, 0);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type, is_previous_staff) VALUES (500, '何清华', 1, 0);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type, is_previous_staff) VALUES (370, '何文广', 1, 0);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type, is_previous_staff) VALUES (440, '何先友', 1, 1);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type, is_previous_staff) VALUES (640, '何晓丽', 1, 1);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type, is_previous_staff) VALUES (110, '侯玉波', 1, 1);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type, is_previous_staff) VALUES (210, '胡金生', 1, 1);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type, is_previous_staff) VALUES (110, '胡理', 1, 0);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type, is_previous_staff) VALUES (110, '胡平', 1, 1);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type, is_previous_staff) VALUES (330, '胡瑜', 1, 0);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type, is_previous_staff) VALUES (610, '姬鸣', 1, 0);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type, is_previous_staff) VALUES (320, '贾林祥', 1, 0);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type, is_previous_staff) VALUES (130, '贾宁', 1, 0);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type, is_previous_staff) VALUES (110, '贾晓明', 1, 1);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type, is_previous_staff) VALUES (110, '蒋毅', 1, 1);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type, is_previous_staff) VALUES (120, '金花', 1, 0);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type, is_previous_staff) VALUES (110, '雷雳', 1, 1);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type, is_previous_staff) VALUES (500, '雷旭', 1, 0);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type, is_previous_staff) VALUES (510, '雷怡', 1, 1);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type, is_previous_staff) VALUES (320, '冷英', 1, 0);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type, is_previous_staff) VALUES (310, '李丹', 1, 1);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type, is_previous_staff) VALUES (440, '李红', 1, 1);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type, is_previous_staff) VALUES (630, '李美华', 1, 1);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type, is_previous_staff) VALUES (320, '李鸣', 1, 0);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type, is_previous_staff) VALUES (120, '李强', 1, 0);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type, is_previous_staff) VALUES (370, '李寿欣', 1, 1);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type, is_previous_staff) VALUES (330, '李伟健', 1, 1);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type, is_previous_staff) VALUES (310, '李卫东', 1, 0);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type, is_previous_staff) VALUES (310, '李先春', 1, 0);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type, is_previous_staff) VALUES (110, '李永娟', 1, 0);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type, is_previous_staff) VALUES (410, '李永鑫', 1, 1);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type, is_previous_staff) VALUES (350, '连榕', 1, 1);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type, is_previous_staff) VALUES (110, '蔺秀云', 1, 0);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type, is_previous_staff) VALUES (110, '刘超', 1, 0);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type, is_previous_staff) VALUES (410, '刘慧瀛', 1, 0);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type, is_previous_staff) VALUES (310, '刘俊升', 1, 0);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type, is_previous_staff) VALUES (110, '刘力', 1, 1);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type, is_previous_staff) VALUES (210, '刘文', 1, 1);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type, is_previous_staff) VALUES (610, '刘旭峰', 1, 0);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type, is_previous_staff) VALUES (110, '刘正奎', 1, 1);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type, is_previous_staff) VALUES (110, '柳昀哲', 1, 0);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type, is_previous_staff) VALUES (510, '卢雄', 1, 0);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type, is_previous_staff) VALUES (310, '陆静怡', 1, 0);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type, is_previous_staff) VALUES (110, '栾胜华', 1, 0);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type, is_previous_staff) VALUES (110, '罗欢', 1, 0);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type, is_previous_staff) VALUES (110, '罗劲', 1, 1);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type, is_previous_staff) VALUES (310, '罗俊龙', 1, 0);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type, is_previous_staff) VALUES (110, '罗良', 1, 0);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type, is_previous_staff) VALUES (210, '罗文波', 1, 1);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type, is_previous_staff) VALUES (500, '吕厚超', 1, 0);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type, is_previous_staff) VALUES (120, '吕小康', 1, 0);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type, is_previous_staff) VALUES (650, '麻超', 1, 0);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type, is_previous_staff) VALUES (540, '马海林', 1, 0);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type, is_previous_staff) VALUES (420, '马红宇', 1, 0);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type, is_previous_staff) VALUES (320, '马向真', 1, 0);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type, is_previous_staff) VALUES (510, '马小红', 1, 0);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type, is_previous_staff) VALUES (530, '马谐', 1, 1);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type, is_previous_staff) VALUES (650, '买合甫来提·坎吉', 1, 1);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type, is_previous_staff) VALUES (310, '孟馥', 1, 0);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type, is_previous_staff) VALUES (350, '孟迎芳', 1, 0);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type, is_previous_staff) VALUES (410, '孟勇', 1, 0);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type, is_previous_staff) VALUES (110, '南云', 1, 0);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type, is_previous_staff) VALUES (440, '聂衍刚', 1, 1);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type, is_previous_staff) VALUES (310, '庞维国', 1, 1);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type, is_previous_staff) VALUES (430, '彭运石', 1, 1);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type, is_previous_staff) VALUES (110, '乔志宏', 1, 0);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type, is_previous_staff) VALUES (110, '秦绍正', 1, 1);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type, is_previous_staff) VALUES (410, '任国防', 1, 0);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type, is_previous_staff) VALUES (320, '任其平', 1, 0);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type, is_previous_staff) VALUES (420, '任志洪', 1, 0);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type, is_previous_staff) VALUES (340, '桑青松', 1, 0);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type, is_previous_staff) VALUES (330, '沈模卫', 1, 1);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type, is_previous_staff) VALUES (370, '司继伟', 1, 0);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type, is_previous_staff) VALUES (330, '孙炳海', 1, 0);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type, is_previous_staff) VALUES (110, '孙向红', 1, 1);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type, is_previous_staff) VALUES (420, '孙晓军', 1, 0);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type, is_previous_staff) VALUES (430, '唐芳贵', 1, 0);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type, is_previous_staff) VALUES (110, '陶沙', 1, 1);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type, is_previous_staff) VALUES (320, '田晓明', 1, 1);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type, is_previous_staff) VALUES (360, '涂冬波', 1, 0);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type, is_previous_staff) VALUES (370, '王大伟', 1, 0);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type, is_previous_staff) VALUES (220, '王海英', 1, 0);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type, is_previous_staff) VALUES (110, '王垒', 1, 1);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type, is_previous_staff) VALUES (110, '王力', 1, 1);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type, is_previous_staff) VALUES (110, '王亮', 1, 0);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type, is_previous_staff) VALUES (410, '王明辉', 1, 0);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type, is_previous_staff) VALUES (440, '王瑞明', 1, 0);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type, is_previous_staff) VALUES (150, '王欣瑜', 1, 0);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type, is_previous_staff) VALUES (140, '王兴超', 1, 0);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type, is_previous_staff) VALUES (370, '王艳郁', 1, 0);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type, is_previous_staff) VALUES (610, '王振宏', 1, 1);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type, is_previous_staff) VALUES (110, '王争艳', 1, 1);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type, is_previous_staff) VALUES (350, '魏玲', 1, 0);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type, is_previous_staff) VALUES (440, '温忠麟', 1, 0);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type, is_previous_staff) VALUES (150, '乌云特娜', 1, 1);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type, is_previous_staff) VALUES (320, '吴继霞', 1, 0);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type, is_previous_staff) VALUES (110, '吴南', 1, 0);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type, is_previous_staff) VALUES (110, '吴艳红', 1, 1);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type, is_previous_staff) VALUES (110, '伍新春', 1, 1);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type, is_previous_staff) VALUES (110, '伍珍', 1, 0);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type, is_previous_staff) VALUES (110, '夏明睿', 1, 0);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type, is_previous_staff) VALUES (620, '夏瑞雪', 1, 0);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type, is_previous_staff) VALUES (460, '肖少北', 1, 1);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type, is_previous_staff) VALUES (110, '谢晓非', 1, 1);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type, is_previous_staff) VALUES (110, '辛自强', 1, 1);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type, is_previous_staff) VALUES (410, '熊建萍', 1, 0);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type, is_previous_staff) VALUES (500, '杨国愉', 1, 0);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type, is_previous_staff) VALUES (120, '杨海波', 1, 1);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type, is_previous_staff) VALUES (320, '杨莉萍', 1, 0);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type, is_previous_staff) VALUES (440, '杨文登', 1, 0);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type, is_previous_staff) VALUES (340, '姚本先', 1, 1);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type, is_previous_staff) VALUES (610, '游旭群', 1, 1);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type, is_previous_staff) VALUES (130, '袁立壮', 1, 0);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type, is_previous_staff) VALUES (330, '臧玉峰', 1, 1);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type, is_previous_staff) VALUES (360, '曾晓青', 1, 0);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type, is_previous_staff) VALUES (110, '张丹', 1, 0);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type, is_previous_staff) VALUES (110, '张建新', 1, 1);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type, is_previous_staff) VALUES (320, '张明', 1, 1);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type, is_previous_staff) VALUES (230, '张守臣', 1, 1);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type, is_previous_staff) VALUES (450, '张姝玥', 1, 1);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type, is_previous_staff) VALUES (440, '张卫', 1, 1);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type, is_previous_staff) VALUES (370, '张文新', 1, 1);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type, is_previous_staff) VALUES (340, '张效初', 1, 0);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type, is_previous_staff) VALUES (220, '张彦彦', 1, 0);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type, is_previous_staff) VALUES (130, '张志杰', 1, 1);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type, is_previous_staff) VALUES (410, '赵国祥', 1, 1);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type, is_previous_staff) VALUES (330, '赵立', 1, 0);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type, is_previous_staff) VALUES (420, '赵庆柏', 1, 0);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type, is_previous_staff) VALUES (520, '赵守盈', 1, 1);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type, is_previous_staff) VALUES (620, '赵鑫', 1, 1);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type, is_previous_staff) VALUES (440, '郑剑虹', 1, 0);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type, is_previous_staff) VALUES (440, '郑希付', 1, 1);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type, is_previous_staff) VALUES (320, '周仁来', 1, 1);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type, is_previous_staff) VALUES (110, '周雯', 1, 0);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type, is_previous_staff) VALUES (310, '周晓林', 1, 1);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type, is_previous_staff) VALUES (330, '周欣悦', 1, 1);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type, is_previous_staff) VALUES (420, '周宗奎', 1, 1);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type, is_previous_staff) VALUES (430, '朱熊兆', 1, 0);
INSERT into config_candidate_info (province_code, candidate_name, candidate_type, is_previous_staff) VALUES (440, '佐斌', 1, 1);
